import { Dimensions, StyleSheet } from 'react-native';
import theme from '../../styles/theme';

const { width: screenWidth } = Dimensions.get('window');

const styles = StyleSheet.create({
  scrollViewContent: {
    paddingHorizontal: 12,
    paddingBottom: 20,
    gap: 16,
  },
  slidesContainer: {
    marginTop: 8,
  },
  slidesContent: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
    gap: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 10,
    paddingHorizontal: 6,
  },
  eventCard: {
    backgroundColor: theme.COLORS.WHITE,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 12,
    width: screenWidth,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 5,
    elevation: 4,
  },
  eventImage: {
    width: '100%',
    height: 180,
    borderRadius: 10,
  },
  eventTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
    marginTop: 10,
    marginBottom: 4,
    textAlign: 'center',
  },
  eventDate: {
    fontSize: 13,
    color: '#4B5563',
    marginTop: 2,
    textAlign: 'center',
  },
  subscribeButton: {
    marginTop: 10,
    backgroundColor: '#5B21B6',
    paddingVertical: 9,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  subscribeButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 10,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 4,
  },
  activeDot: {
    backgroundColor: '#5B21B6',
  },
  agendaContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  agendaTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  agendaDatesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 2,
  },
  agendaDateChip: {
    borderRadius: 999,
    backgroundColor: '#EDE9FE',
    borderWidth: 1,
    borderColor: '#C4B5FD',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  agendaDateText: {
    fontSize: 12,
    color: '#4C1D95',
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  agendaList: {
    marginTop: 10,
    gap: 8,
    paddingHorizontal: 2,
  },
  agendaItem: {
    borderRadius: 8,
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  agendaItemTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
  },
  agendaItemMeta: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  agendaEmpty: {
    textAlign: 'center',
    color: '#6B7280',
    fontSize: 13,
    paddingVertical: 8,
  },
  videoCard: {
    backgroundColor: theme.COLORS.WHITE,
    borderRadius: 10,
    marginRight: 12,
    padding: 8,
    width: 220,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 4,
    elevation: 4,
  },
  videoThumbnail: {
    width: '100%',
    height: 120,
    borderRadius: 8,
  },
  videoTitle: {
    fontSize: 13,
    color: '#111827',
    marginTop: 8,
    minHeight: 36,
  },
  watchButton: {
    marginTop: 10,
    borderRadius: 8,
    backgroundColor: '#DC2626',
    paddingVertical: 8,
    alignItems: 'center',
  },
  watchButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  videoEmptyState: {
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 14,
    marginHorizontal: 6,
  },
  videoEmptyTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  videoEmptyText: {
    fontSize: 12,
    color: '#6B7280',
    lineHeight: 18,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  webviewContainer: {
    width: '92%',
    height: '70%',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 10,
  },
  webview: {
    flex: 1,
    borderRadius: 10,
  },
  closeButton: {
    backgroundColor: '#f44336',
    padding: 10,
    borderRadius: 8,
    marginTop: 10,
  },
  closeButtonText: {
    color: 'white',
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '700',
  },
  tithesContainer: {
    backgroundColor: theme.COLORS.PURPLE_CARD,
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
  },
  tithesTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: theme.COLORS.WHITE,
    marginBottom: 8,
  },
  tithesText: {
    fontSize: 16,
    color: theme.COLORS.WHITE,
    textAlign: 'center',
  },
  offerButton: {
    marginTop: 12,
    backgroundColor: '#007BFF',
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: 'center',
  },
  offerButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  pixDataText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
    marginBottom: 10,
  },
  pixData: {
    fontSize: 16,
    color: 'black',
    marginBottom: 20,
  },
  modalContent: {
    width: '80%',
    backgroundColor: '#fff',
    padding: 20,
    borderRadius: 8,
    alignItems: 'center',
  },
});

export default styles;
