import { AppRole } from "../utils/role";

export type ManagementModule = {
  id: string;
  title: string;
  description: string;
  roles: AppRole[];
  icon: string;
  routeName?: string;
};

export const MANAGEMENT_MODULES: ManagementModule[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    description: "Visao geral da igreja",
    roles: ["pastor", "obreiro", "discipulador", "lider"],
    icon: "home-outline",
    routeName: "Inicio",
  },
  {
    id: "cells",
    title: "Minhas Celulas",
    description: "Mapa e acompanhamento",
    roles: ["pastor", "lider", "discipulador"],
    icon: "map-outline",
    routeName: "CellGroupMap",
  },
  {
    id: "leaders",
    title: "Lideres",
    description: "Gestao de lideres",
    roles: ["pastor", "discipulador"],
    icon: "people-outline",
  },
  {
    id: "disciples",
    title: "Discipuladores",
    description: "Gestao de discipuladores",
    roles: ["pastor"],
    icon: "person-add-outline",
  },
  {
    id: "monthly-reports",
    title: "Relatorio Celula Mensal",
    description: "Relatorios enviados",
    roles: ["pastor", "obreiro", "discipulador", "lider"],
    icon: "document-text-outline",
    routeName: "Relatorios",
  },
  {
    id: "weekly-reports",
    title: "Relatorio Celula Semanal",
    description: "Fluxo semanal de acompanhamento",
    roles: ["pastor", "obreiro", "discipulador", "lider"],
    icon: "calendar-outline",
  },
  {
    id: "service-reports",
    title: "Relatorios de Culto",
    description: "Indicadores de culto",
    roles: ["pastor", "lider"],
    icon: "business-outline",
  },
  {
    id: "courses",
    title: "Cursos",
    description: "Trilho e edificacao",
    roles: ["pastor", "obreiro", "discipulador", "lider"],
    icon: "school-outline",
    routeName: "Edificacao",
  },
  {
    id: "agenda",
    title: "Agenda",
    description: "Eventos e compromissos",
    roles: ["pastor", "obreiro", "discipulador", "lider"],
    icon: "calendar-clear-outline",
    routeName: "AgendaManagement",
  },
  {
    id: "financial",
    title: "Financeiro",
    description: "Fluxo financeiro",
    roles: ["pastor", "obreiro"],
    icon: "wallet-outline",
    routeName: "FinancialManagement",
  },
  {
    id: "dizimistas",
    title: "Dizimistas",
    description: "Gestao de dizimistas",
    roles: ["pastor", "obreiro"],
    icon: "cash-outline",
    routeName: "DizimistasManagement",
  },
  {
    id: "baptism",
    title: "Batismo",
    description: "Acompanhamento de batizantes",
    roles: ["pastor", "obreiro", "discipulador", "lider"],
    icon: "water-outline",
    routeName: "BaptismManagement",
  },
  {
    id: "schedules",
    title: "Escalas",
    description: "Escalas ministeriais",
    roles: ["pastor", "discipulador", "lider"],
    icon: "list-outline",
    routeName: "SchedulesManagement",
  },
  {
    id: "encounter",
    title: "Encontro com Deus",
    description: "Gestao de encontros",
    roles: ["pastor", "discipulador"],
    icon: "heart-outline",
    routeName: "EncounterEventsManagement",
  },
  {
    id: "statistics",
    title: "Estatisticas",
    description: "Painel de indicadores",
    roles: ["pastor", "obreiro", "discipulador"],
    icon: "stats-chart-outline",
    routeName: "Inicio",
  },
  {
    id: "church-management",
    title: "Gerenciar Igreja",
    description: "Cadastros administrativos",
    roles: ["pastor", "obreiro"],
    icon: "construct-outline",
  },
];

export const QUICK_ACTIONS: Partial<Record<AppRole, ManagementModule[]>> = {
  lider: [
    {
      id: "quick-create-report",
      title: "Criar Relatorio",
      description: "Registrar relatorio da celula",
      roles: ["lider"],
      icon: "add-circle-outline",
      routeName: "CreateReport",
    },
    {
      id: "quick-monthly-reports",
      title: "Ver Relatorios",
      description: "Acompanhar historico",
      roles: ["lider"],
      icon: "documents-outline",
      routeName: "Relatorios",
    },
    {
      id: "quick-agenda-lider",
      title: "Agenda",
      description: "Ver eventos ativos",
      roles: ["lider"],
      icon: "calendar-clear-outline",
      routeName: "AgendaManagement",
    },
    {
      id: "quick-batismo-lider",
      title: "Batismo",
      description: "Acompanhar inscritos",
      roles: ["lider"],
      icon: "water-outline",
      routeName: "BaptismManagement",
    },
  ],
  discipulador: [
    {
      id: "quick-register-cell",
      title: "Cadastrar Celula",
      description: "Adicionar celula no mapa",
      roles: ["discipulador"],
      icon: "location-outline",
      routeName: "CadastrarCelula",
    },
    {
      id: "quick-cell-map",
      title: "Mapa de Celulas",
      description: "Visualizar celulas",
      roles: ["discipulador"],
      icon: "map-outline",
      routeName: "CellGroupMap",
    },
    {
      id: "quick-schedules-discipulador",
      title: "Escalas",
      description: "Escalas da semana",
      roles: ["discipulador"],
      icon: "list-outline",
      routeName: "SchedulesManagement",
    },
    {
      id: "quick-encounter-discipulador",
      title: "Encontro",
      description: "Eventos de encontro",
      roles: ["discipulador"],
      icon: "heart-outline",
      routeName: "EncounterEventsManagement",
    },
  ],
  obreiro: [
    {
      id: "quick-monthly-reports-obreiro",
      title: "Relatorios",
      description: "Acompanhar celulas",
      roles: ["obreiro"],
      icon: "document-text-outline",
      routeName: "Relatorios",
    },
    {
      id: "quick-financial-obreiro",
      title: "Financeiro",
      description: "Fluxo financeiro",
      roles: ["obreiro"],
      icon: "wallet-outline",
      routeName: "FinancialManagement",
    },
    {
      id: "quick-dizimistas-obreiro",
      title: "Dizimistas",
      description: "Cadastros de dizimo",
      roles: ["obreiro"],
      icon: "cash-outline",
      routeName: "DizimistasManagement",
    },
  ],
  pastor: [
    {
      id: "quick-monthly-reports-pastor",
      title: "Relatorios",
      description: "Visao geral da rede",
      roles: ["pastor"],
      icon: "document-text-outline",
      routeName: "Relatorios",
    },
    {
      id: "quick-cell-map-pastor",
      title: "Mapa de Celulas",
      description: "Visualizar rede",
      roles: ["pastor"],
      icon: "map-outline",
      routeName: "CellGroupMap",
    },
    {
      id: "quick-agenda-pastor",
      title: "Agenda",
      description: "Gerir eventos da igreja",
      roles: ["pastor"],
      icon: "calendar-clear-outline",
      routeName: "AgendaManagement",
    },
    {
      id: "quick-financial-pastor",
      title: "Financeiro",
      description: "Controle financeiro",
      roles: ["pastor"],
      icon: "wallet-outline",
      routeName: "FinancialManagement",
    },
    {
      id: "quick-encounter-pastor",
      title: "Encontro",
      description: "Eventos de encontro",
      roles: ["pastor"],
      icon: "heart-outline",
      routeName: "EncounterEventsManagement",
    },
  ],
};
